algoritmo "Procedimento novo"
var
   Idade: Inteiro
   
Procedimento Topo()
Inicio
      Limpatela
      EscrevaL("----------------------------")
      EscrevaL("I D A D E  DE  P E S S O A S")
      EscrevaL("----------------------------")

FimProcedimento

procedimento LendoIDade()
Inicio
   EscrevaL("Digite sua Idade")
   Leia (Idade)
   
FimProcedimento
inicio
      Topo()
      LendoIDade()
      
      EscrevaL("Sua Idade eh ", Idade)
fimalgoritmo